name = "EODS"
prefix = "eods"
author = "Christiansen"
files = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README.md",
    "docs/README_DE.md",
    "docs/README_PL.md",
    "docs/README.zh-TW.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_proj_templ_ca.paa",
    "meta.cpp"
]

key_name = "{{prefix}}_{{version}}"


releasebuild = [
    "@zip eods_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]
